name: Ermetic IaC Scan Workflow

on:
  push:
    branches:
      - main  # Trigger scan when changes are pushed to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger scan on PRs targeting 'main'
  # You can also use other events like schedule (cron) to trigger the scan periodically

jobs:
  ermetic-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code in your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Scan with Ermetic
      - name: Scan with Ermetic
        uses: ermetic/actions/iac/scan@v1
        with:
          api-token: ${{ secrets.TENABLE_API_TOKEN }}  # GitHub secret containing your Ermetic API token
          api-url: https://uk.app.ermetic.com  # The Ermetic API URL (update based on your region, if needed)

      # Optional: You can add more steps to handle scan results, notifications, or failure conditions
